---
- name: "[{{ item.name }}] Set interface"
  community.general.xml:
    pretty_print: true
    path: "{{ local_file }}"
    xpath: "{{ xpath }}/{{ item.name }}/if"
    value: "{{ item.iface }}"

- name: "[{{ item.name }}] Set description"
  community.general.xml:
    pretty_print: true
    path: "{{ local_file }}"
    xpath: "{{ xpath }}/{{ item.name }}/descr"
    value: "{{ item.description }}"
  when: item.description is defined

- name: "[{{ item.name }}] Set enabled status"
  community.general.xml:
    pretty_print: true
    path: "{{ local_file }}"
    xpath: "{{ xpath }}/{{ item.name }}/enable"
    value: "{{ '1' if item.enabled else '0' }}"

- name: "[{{ item.name }}] Set lock status"
  community.general.xml:
    pretty_print: true
    path: "{{ local_file }}"
    xpath: "{{ xpath }}/{{ item.name }}/lock"
    value: "{{ '1' if item.lock else '0' }}"

- name: "[{{ item.name }}] Set IP address"
  community.general.xml:
    pretty_print: true
    path: "{{ local_file }}"
    xpath: "{{ xpath }}/{{ item.name }}/ipaddr"
    value: "{{ item.address }}"

- name: "[{{ item.name }}] Set subnet"
  community.general.xml:
    pretty_print: true
    path: "{{ local_file }}"
    xpath: "{{ xpath }}/{{ item.name }}/subnet"
    value: "{{ item.subnet }}"

- name: "[{{ item.name }}] Block private networks"
  community.general.xml:
    pretty_print: true
    path: "{{ local_file }}"
    xpath: "{{ xpath }}/{{ item.name }}/blockpriv"
    state: "{{ 'present' if item.block_private else 'absent' }}"

- name: "[{{ item.name }}] Block bogon networks"
  community.general.xml:
    pretty_print: true
    path: "{{ local_file }}"
    xpath: "{{ xpath }}/{{ item.name }}/blockbogons"
    state: "{{ 'present' if item.block_bogon else 'absent' }}"

- name: "[{{ item.name }}] Set default gateway"
  community.general.xml:
    pretty_print: true
    path: "{{ local_file }}"
    xpath: "{{ xpath }}/{{ item.name }}/gateway"
    value: "{{ item.gateway }}"
  when: item.gateway is defined
