---
- name: "[PRE-TASK] Fetch config.xml from remote host"
  ansible.builtin.fetch:
    src: "{{ config_file }}"
    dest: "{{ local_file }}"
    flat: true

- name: Import interface tasks
  delegate_to: localhost
  notify: Upload config
  ansible.builtin.include_tasks: config.yml
  with_items: "{{ opnsense_interfaces }}"

- name: Flush Handlers
  ansible.builtin.meta: flush_handlers
